version: '3.5'

services:

  jupiter-spark:
    container_name: jupyter-spark
    image: jupyter/all-spark-notebook
    volumes:
      - ../../notebooks/jupyter/:/home/jovyan/:rw
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
    hostname: localhost
    environment:
      GRANT_SUDO: "yes"
    user: root